name: _
publish_to: none
environment:
  sdk: ^3.6.0
workspace:
  - geolocator
  - geolocator_android
  - geolocator_apple
  - geolocator_linux
  - geolocator_platform_interface
  - geolocator_web
  - geolocator_windows
